# Site settings
title: Vanessa Gill
email: vanessa.a.gill@gmail.com
url: https://cnvrsepnk.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 303030 #FD6E8A
  secondary-dark: 222222 #A2122F
  headers: f00
  links: e8bc2f

# Footer settings
footer:
  copyright: Vanessa Gill || =^. .^=
  location: Location
  social: Connect With Me
  credits: Twitter

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/cnvrsepnk
  - title: facebook
    url:
  - title: facebook
    url: http://www.facebook.com/cnvrsepnk
  - title: linkedin
    url: http://www.linkedin.com/pub/vanessa-gill/13/63a/98b
  - title: github
    url: http://github.com/cnvrsepnk

# Postal address (add as many lines as necessary)
address:
  - line: Somewhere in Scenic Seattle

# Credits content
credits: 'Twitter feed will go here...'

# Build settings
markdown: kramdown
permalink: pretty
